### ISSUE TITLE
Lots of NPEs in UserSocket.getClientConfig

### ISSUE THREAD

**Issue by csmith** [DFBnc/DFBnc#128]
Bouncer stops talking to clients after they connect:

<2017-01-27 17:55:19> [Error] Unexpected exception during processLine
<2017-01-27 17:55:19> [Error] 	Stack trace: java.lang.NullPointerException
	at com.dfbnc.sockets.UserSocket.getClientConfig(UserSocket.java:502)
	at com.dfbnc.servers.irc.IRCConnectionHandler.sendBackbuffer(IRCConnectionHandler.java:1747)
	at com.dfbnc.servers.irc.IRCConnectionHandler.sendPrivateBackbuffer(IRCConnectionHandler.java:1728)
	at com.dfbnc.servers.irc.IRCConnectionHandler.userConnected(IRCConnectionHandler.java:1628)
	at com.dfbnc.Account.userConnected(Account.java:177)
	at com.dfbnc.authentication.Authenticator.handleSuccessfulAuth(Authenticator.java:239)
	at com.dfbnc.authentication.Authenticator.authenticate(Authenticator.java:186)
	at com.dfbnc.sockets.UserSocket.checkAuthStatus(UserSocket.java:939)
	at com.dfbnc.sockets.UserSocket.processNonAuthenticated(UserSocket.java:924)
	at com.dfbnc.sockets.UserSocket.processLine(UserSocket.java:889)
	at com.dfbnc.sockets.UserSocket.processLine(UserSocket.java:864)
	at com.dfbnc.sockets.SocketWrapper.handleSelectionKey(SocketWrapper.java:405)
	at com.dfbnc.sockets.ConnectedSocket.processSelectionKey(ConnectedSocket.java:243)
	at com.dfbnc.sockets.SocketSelector.run(SocketSelector.java:142)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "Timer-4" java.lang.NullPointerException
	at com.dfbnc.sockets.UserSocket.getClientConfig(UserSocket.java:502)
	at com.dfbnc.servers.irc.IRCConnectionHandler$2.run(IRCConnectionHandler.java:1588)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by ShaneMcC** [comment]
Pretty sure this was fixed in https://github.com/DFBnc/DFBnc/commit/5ea61bfe890348567479fba4ac28455573419a0c
